apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Authentik Core Secret Key
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        # Postgres Password (for the bundled postgres)
        postgresql-password: "{{ .AUTHENTIK_POSTGRESQL_PASSWORD }}"
        postgresql-postgres-password: "{{ .AUTHENTIK_POSTGRESQL_PASSWORD }}"
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: 9af9ea6b-f1ba-4e03-8a5a-b3a00079a73d
        property: password
    - secretKey: AUTHENTIK_POSTGRESQL_PASSWORD
      remoteRef:
        key: 9af9ea6b-f1ba-4e03-8a5a-b3a00079a73d
        property: password
