apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-core-secrets
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: authentik-core-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_REDIS__PASSWORD: "{{ .AUTHENTIK_REDIS_PASSWORD }}"
        redis-password: "{{ .AUTHENTIK_REDIS_PASSWORD }}"
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: 9af9ea6b-f1ba-4e03-8a5a-b3a00079a73d
        property: password
    - secretKey: AUTHENTIK_REDIS_PASSWORD
      remoteRef:
        key: 9af9ea6b-f1ba-4e03-8a5a-b3a00079a73d
        property: password
