apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

resources:
  - namespace.yaml
  - external-secret.yaml
  - database.yaml
  - httproute.yaml
  - blueprints.yaml

helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io
    version: 2025.10.2
    releaseName: authentik
    namespace: authentik
    valuesFile: values.yaml
