apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      organizationID: "6ce343f0-efbd-453f-836a-b39f0088b290"
      projectID: "e3b0b2ac-19f2-464d-a859-b39f00892f97"
      apiURL: "https://api.bitwarden.eu"
      identityURL: "https://identity.bitwarden.eu"
      bitwardenServerSDKURL: "http://external-secrets-bitwarden-sdk-server.external-secrets.svc.cluster.local:9998"
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            key: token
