apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    bitwarden-sdk:
      organizationId: "6ce343f0-efbd-453f-836a-b39f0088b290"
      projectId: "e3b0b2ac-19f2-464d-a859-b39f00892f97"
      apiUrl: "https://api.bitwarden.eu"
      identityUrl: "https://identity.bitwarden.eu"
      auth:
        accessToken:
          name: bitwarden-access-token
          key: token
