apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-wildcard
  namespace: gateway
spec:
  dnsNames:
    - "*.rosenvall.se"
    - rosenvall.se
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: cert-wildcard
  usages:
    - digital signature
    - key encipherment
